### ISSUE TITLE
Replacing images

### ISSUE THREAD

**Issue by shuhrat02** [xdavidhu/lanGhost#14]
/replaceimg ip doesn't work

> 📷 Please send the image you want to replace others with:
> *.jpg
> 
> lanGhost, [01.03.18 15:04]
> Starting attack with ID: 1
> 
> lanGhost, [01.03.18 15:04]
> Type /stop 1 to stop the attack.
> 
> lanGhost, [01.03.18 15:04]
> 🔥 Replacing images for 172.28.ip.212...
> 
> lanGhost, [01.03.18 15:04]
> 🔥 Attacks running:
> 
> ID: 1 ➖ replaceimg ➖ 172.28.ip.212

Terminal:
[+] Routing 172.28.ip.212 into mitmdump with iptables...
[+] ARP Spoofing 172.28.ip.212...

Bot says, that everything works fine. But actually nothing happens, during the attack.

tested on http sites, like bbc.com

**Comment by xdavidhu** [comment]
Hi, ARP spoofing can sometimes work problematically depending on your network setup. As I said for other people, I unfortunately can't debug that remotely.

As for the actualy image replacing, bbc.com uses https for images, only the basic site is in HTTP. I tried testing that before and had this same problem. Try it on some image which you are sure is HTTP.
