### ISSUE TITLE
 target can not surf

### ISSUE THREAD

**Issue by ChandraOrbit** [xdavidhu/lanGhost#16]
all attacks cause the target can not surf.
Is it because all sites already use https or there is an error in your script so that there is a jam.
according to my logic should lanGhost be able to throw into the internet when switching DNS.

**Comment by xdavidhu** [comment]
Hi!

lanGhost should only stop devices from accessing the internet if you run the `/kill` command. If you are getting connection errors without the kill command, maybe there is an issue with the signal strength, the PI's network connection, the whole network's stability. There can be a lot of reasons why this issue happens, and unfortunately I cant debug it remotely. Try running lanGhost on an other network/PI, and see if the issue still persists.
