### ISSUE TITLE
lanGhost in Termux

### ISSUE THREAD

**Issue by extbodyan** [xdavidhu/lanGhost#9]
Can the lanGhost package be installed on Termux?

**Comment by extbodyan** [comment]
I have the same problem as bingbong553 "
No module named 'telegram' # 7 This is more likely due to the fact that Termux does not have python3 & python3-pip packages

**Comment by xdavidhu** [comment]
Termux is an Android terminal emulator, so you would have to install every dependency on your Android device to make it work which could be extremely difficult if not impossible. I would suggest you to install lanGhost on a Raspberry Pi, because it's tested/made for that purpose.
